### PR TITLE
fix: update/delete should not fail when table has multi-column primary key

### LINKED ISSUE #31: soft delete should support multiple keys properly
```
SEVERE	load_54	2024-03-07T05:47:44.005Z	DestinationLoader#retry	INTERNAL: WriteBatch endpoint failed for schema <repo>, table <repo_team>:Error deleting rows from table <"my_db"."repo"."repo_team">:Parser Error: syntax error at or near ","
LINE 1: ..." = localmem.arrow_view."repository_id", repo_team."team_id" = localmem.arrow_...
```

### PR DESCRIPTION
**Pull request by elefeint**
Joining multiple column clauses in WHERE columns should be done with an " AND ", not with ", ". 

Fixes #31

### CODE REVIEW

File: test/integration/test_server.cpp [hunk 1]
```diff
@@ -594,9 +612,122 @@ TEST_CASE("CreateTable with multiple primary keys", "[integration]") {
...
+    REQUIRE(res->GetValue(2, 1) == "second row");
+
+    REQUIRE(res->GetValue(0, 2) == 3);
+    REQUIRE(res->GetValue(1, 2) == 300);
+    REQUIRE(res->GetValue(2, 2) == "third row");
+  }
+
+  {
+    // update
+    ::fivetran_sdk::WriteBatchRequest request;
```
Comment (awitten1) [inline test/integration/test_server.cpp:665]: Out of curiosity where is this fivetran code coming from? Are we generating it from https://github.com/fivetran/fivetran_sdk ?

**Review by awitten1 — APPROVED** [review]
LGTM!

File: test/integration/test_server.cpp (hunk 1 above)
Comment (awitten1) [reply test/integration/test_server.cpp:665]: Nvm just read through the build files and I see!
